### PR TITLE
Added the HSL color space.

### PR DESCRIPTION
**Pull request by pkulak**
After I wrote all this I noticed that HCL may be very similar, but, I got it all working, so might as well contribute.

### CODE REVIEW

**Comment by belak** [comment]
It would be really nice to have this. Is HSL still on the roadmap.

**Comment by lucasb-eyer** [comment]
I actually didn't plan to merge the HSL part because I actively want to discourage use of HSL. It's a broken color system, which I try to argue in the README.

But I guess sometimes one doesn't have a choice? I'm actually open to merging it now, if the OP is willing to rebase and force-push (`git rebase master` and `git push --force` while on this branch.) as well as to "fix" the formatting of the test (it was nicely aligned previously, probably got destroyed by gofmt).

**Comment by belak** [comment]
Yeah, that's the situation I'm in. I'm integrating with a system that needs to provide HSL for legacy support... and I'm trying to avoid including one library for most color formats and add an additional one just for that legacy support.

On the topic of those test tables: is there a way to format them such that gofmt wouldn't reformat them, but still make them readable?

**Comment by lucasb-eyer** [comment]
I was not able to find a way to mark a section as "do not touch pls gofmt", but I really want to keep the alignment for the test, as it helped me visually spot mistakes!

Since you are in this situation, I will definitely merge this. If the OP doesn't have the time for these small fixes, I will do them and rebase myself sometime in the next days. Please do ping me again in case I forget to do so!

**Comment by lucasb-eyer** [comment]
Merged manually with the identation fix while keeping history and credit as good as I can, see 70b6775 and 8b65a2a. It seems Github doesn't recognize that though, so closing this PR.

**Comment by pkulak** [comment]
Hey, sorry about that! I just got back from vacation and missed this whole thread. Thanks for doing the work and merging it in!

**Comment by lucasb-eyer** [comment]
Oh no worries at all. I tried to make sure you still get your commit's credit at least :smile:

**Comment by belak** [comment]
Thanks! Seems to work well.

**Pull request closed without merging**
