### PR TITLE
Introduce a function for sorting colors

### PR DESCRIPTION
**Pull request by spakin**
I figured I'd take a stab at addressing the [`README.md`](https://github.com/lucasb-eyer/go-colorful/blob/a461bc924c8f80f067a42e4f26a561984f56daf7/README.md)'s call for a sort function:

> There are a few features which are currently missing and might be useful. I just haven't implemented them yet because I didn't have the need for it. Pull requests welcome.
>
> * Sorting colors (potentially using above mentioned distances)

This pull request introduces a new `Sorted` function that sorts colors using the CIEDE2000 distance.  Inspired by ["The incredibly challenging task of sorting colours"](https://www.alanzucconi.com/2015/09/30/colour-sorting/), the implementation sorts by taking a traveling salesman tour around the provided colors, starting (and therefore ending) with the color closest to black.  Because the [traveling salesman problem](https://en.wikipedia.org/wiki/Travelling_salesman_problem) is NP-hard, `Sorted` uses an approximation based on a [minimum spanning tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree), whose output is within 2x of optimal.

In addition to the `Sorted` function itself (defined in a new `sort.go` file), the pull request provides

* a simple test case (`sort_test.go`),
* documentation (within the `README.md` file),
* an image for the documentation illustrating the effect of `Sorted`, and
* the code that produced that image.

I hope this is what you had in mind for a sorting function for Go-Colorful.  Enjoy!

### CODE REVIEW

**Comment by spakin** [comment]
By the way, here's a pretty picture (added to the `README.md` file) showing what `Sorted` does:

colorsort

The first row represents random, unsorted colors.  The second row is what you'd get if you were to sort by channel.  In this case I sorted by L* then h° then C*, but the result, with the distracting pinstriping, would be similar with any color space and any channel ordering.  The third row was produced by the `Sorted` function from the pull request.  It's not perfect, but it's certainly a lot less pinstripey.

**Comment by makeworld-the-better-one** [comment]
Thanks for your high-quality PR. This is definitely a pretty interesting function. I'm happy to merge it in, but do you think it's possible to make without the `disjoint` dependency? Right now we have no deps and it'd be great to keep that.

**Comment by spakin** [comment]
I can do that.  [`disjoint`](https://github.com/spakin/disjoint) is pretty small so it's not too big of a deal.

**Comment by spakin** [comment]
I *think* my changes made it into the pull request and are ready for your review.  This is the first time I've updated a pull request so please let me know if you don't see the dependency-free version of my submission so I can try to figure out what I'm supposed to do on GitHub.

**Comment by makeworld-the-better-one** [comment]
Yep, they've made it in:

image

I'll merge this. Thanks!

**Comment by spakin** [comment]
Cool!  Thanks for merging.

**Pull request merged**
