### PR TITLE
Add HexColor implementing database/sql.Scanner and database/sql/drive…

### PR DESCRIPTION
**Pull request by twpayne**
…r.Value interfaces

### CODE REVIEW

**Comment by twpayne** [comment]
The Travis build fails with
```
$ $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
flag needs an argument: -repotoken
```
This seems unrelated to the changes in this PR.

**Comment by lucasb-eyer** [comment]
This looks good and useful, thanks for contributing back!

The failure is due to me still learning the details of TravisCI :smile: Would you mind re-basing this PR so I can see if tests in PRs work now? While doing so, feel free to add yourself to the list of contributors in the [README here](https://github.com/lucasb-eyer/go-colorful#who).

**Comment by twpayne** [comment]
Done. Travis still fails. It looks like the `$COVERALLS_TOKEN` environment variable is not set.

**Comment by lucasb-eyer** [comment]
Argh! I'm merging and will continue testing travis on my own. Thank you for the contribution!

**Pull request merged**
