### PR TITLE
Dramatically improve "Fast" linear-RGB conversions.

### PR DESCRIPTION
**Pull request by lucasb-eyer**
This is following the discussion in #18.
Documentation and a notebook for deriving the constants will follow.

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
For reference, the benchmark values on my laptop (i7) are:

```
><((("> go test -bench .
Testing up to 100 palettes may take a while...
Done with that, but more tests to run.
BenchmarkColorToLinear-8       	 5000000	       335 ns/op
BenchmarkFastColorToLinear-8   	20000000	        75.6 ns/op
BenchmarkLinearToColor-8       	 5000000	       334 ns/op
BenchmarkFastLinearToColor-8   	20000000	        83.4 ns/op
PASS
ok  	github.com/lucasb-eyer/go-colorful	21.607s
```

which I'd call a success, given the accuracy is still within ~2 RGB values (out of 255)

**Comment by ZirconiumX** [comment]
Very well done! It's actually beginning to look feasible to try out using L\*a\*b\* in a large(ish) render. I do have a few algorithmic flaws of my own to try to resolve, like comparing a pair of points multiple times in a pass, but still, thank you very much!

**Comment by ZirconiumX** [comment]
You misspelt "tight" in 43afed8, @lucasb-eyer.

**Comment by lucasb-eyer** [comment]
Oh, thanks for pointing out the typo, I missed that comment! Will fix in master.

**Pull request merged**
