### PR TITLE
gofmt all sources

### PR DESCRIPTION
**Pull request by muesli**
Since I've started working on improving the `MakeColor` situation, I noticed that some source files weren't formatted by gofmt, which resulted in huge parts of the existing code being automatically rewritten by my IDE every time I save.

Seeing how this became an absolute convention in the Go world, and to make it easier for me and others to contribute to the project, I hope you're cool with this one, big format patch.

### CODE REVIEW

**Comment by muesli** [comment]
Any update on this one? I have a few more patches lining up, but they're obviously all in the go-fmt'd format, so I'm still holding off on submitting them as PRs.

**Comment by lucasb-eyer** [comment]
Sorry for the delay, I'm traveling :world_map: and lost track of it.

I strongly disagree with your IDE in that case, is there no option to turn this off on a per-project basis?

I would prefer not to merge this, as such commits really screw with git blame and friends, and I'm generally not a fan of that. If it's a big hassle for your other pending PRs, then I may agree merging it on a good day. But please leave structured tables such as that in `colors_test.go` stay intact. The alignment there helps catch bugs and makes editing easier.

**Comment by muesli** [comment]
I can turn this setting off, of course, but to be honest I wouldn't want to. I consider gofmt one of Go's strongest features, since it makes it

1. easier to read code you didn't write yourself: everyone's code looks familiar
2. easier to write code: I don't have to worry about getting the conventions right
3. removes the need for controversial coding style discussions

I know it's a bit hard to swallow this pill when you already got a codebase of several thousand lines, but I still consider it the only viable way to collaborate:

We’ve had decades of endless arguments and debates about the correct coding style. Go has done away with these endless debates once and for all by shipping a formatter that ensures that all go code follows the exact same format.

Maybe you'd feel better if you committed those formatting changes? Seeing how there are only four other contributors and 99% of git blame returns your name anyway, not much would change in that regard.

A personal note: I can understand your resentment perfectly well: when I started out with Go, its styling conventions also bothered me, because they just weren't mine and the codebase didn't look like my own code. In the long term, though, and especially when you're working with several other people, you realize that it doesn't matter which coding conventions people stick to, as long as they stick to one well defined standard. `gofmt` is exactly that.

**Comment by lucasb-eyer** [comment]
I don't really mind the change in style, so seeing this argued so strongly, it makes sense for me to change my mind and accept this PR.

Still, I'd like to have the table in `colors_test.go` stay aligned, if you could remove that diff from the commit (only the table, i.e. lines 48-62, and then squash/force-push) I'll hit the merge button.

Thanks!

**Comment by muesli** [comment]
@lucasb-eyer Happy to! Pushed an update, let me know if that's what you expected.

**Comment by lucasb-eyer** [comment]
Yup, exactly. Thanks!

PS: I'll still be on the road the next days so don't expect quick answers to your upcoming PRs, but know that I do appreciate! :+1:

**Pull request merged**
