### PR TITLE
Add BlendLrgb()

### PR DESCRIPTION
**Pull request by mazznoer**
blend-modes-4

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
@mazznoer Thanks for this PR! I have a couple requests.

- Could you rename to `BlendLinearRGB`? This matches the rest of the library
- Could you provided some documentation for the function? Explain why blending in linear RGB might be useful

**Comment by mazznoer** [comment]
`BlendLinearRGB` or `BlendLinearRgb` ?

**Comment by makeworld-the-better-one** [comment]
You're right, it should be `BlendLinearRgb` to match the rest of the library.

**Comment by makeworld-the-better-one** [comment]
Great, thanks!

**Pull request merged**
